# Generated by Django 3.2.8 on 2021-11-06 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('sobrenome', models.CharField(max_length=20)),
                ('dataNascimento', models.DateField(max_length=10, verbose_name='Data de Nascimento')),
                ('endereco', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=20)),
                ('cidade', models.CharField(max_length=20)),
                ('telefonefixo', models.CharField(max_length=20, verbose_name='Telefone Fixo')),
                ('celular', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField(verbose_name='Quantidade (l)')),
                ('descricao', models.CharField(max_length=300, verbose_name='Descrição')),
                ('d_celular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.doadores')),
            ],
        ),
    ]
