# Generated by Django 3.2.8 on 2021-11-12 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_auto_20211112_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doacao',
            name='d_celular',
        ),
    ]
