# Generated by Django 3.2.8 on 2021-11-16 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastros', '0008_auto_20211115_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacao',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doadores',
            name='bairro',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doadores',
            name='celular',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='doadores',
            name='cidade',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doadores',
            name='complemento',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='doadores',
            name='dataNascimento',
            field=models.DateField(max_length=10, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='doadores',
            name='endereco',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doadores',
            name='nome',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doadores',
            name='numero',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='doadores',
            name='sobrenome',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doadores',
            name='telefonefixo',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='Telefone Fixo'),
        ),
        migrations.AlterField(
            model_name='doadores',
            name='username',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
