# Generated by Django 3.2.8 on 2021-11-16 15:12

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0011_alter_doadores_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doadores',
            name='username',
            field=models.CharField(max_length=20, unique=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
