# Generated by Django 3.2.7 on 2021-11-19 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastros', '0014_doacaolist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doadores',
            name='username',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
