# Generated by Django 3.2.7 on 2021-11-19 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0015_alter_doadores_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doacao',
            old_name='username',
            new_name='username_id',
        ),
        migrations.RenameField(
            model_name='doadores',
            old_name='username',
            new_name='username_id',
        ),
    ]
